### ISSUE TITLE
could you take a look

### ISSUE THREAD

**Issue by WhiskyModz** [reveny/Android-DLL-Injector#1]
![Screenshot_20221007-162041_LogCat](https://user-images.githubusercontent.com/96978959/194565138-7272134a-1d2a-4c12-a5d8-19c678501577.png)
how can i fix this error?

**Comment by reveny** [comment]
Fixed. Please download the newest version

**Comment by WhiskyModz** [comment]
![Screenshot_20221008-152150_LogCat](https://user-images.githubusercontent.com/96978959/194707661-5d688d4b-db80-445d-bdfd-40bb418c45f0.png)
working

**Comment by WhiskyModz** [comment]
I tried for polarimgui, I got Inject successful result, but imgui did not appear on the screen

**Comment by reveny** [comment]
That's not an issue with my Injector. Please contact the owner of polarimgui for help with that.

**Comment by WhiskyModz** [comment]
Can you help me with something?
I want to replace the Java part of the project. I want to remove the pkgname selection and the lib path selection. I want the application to take the lib from the lib files and copy it to the local/tmp path and give it 777 permission.

**Comment by WhiskyModz** [comment]
Add Shell.su("chmod 777 " + file.getName).exec();

**Comment by bjmkk** [comment]
Which log saver is this
