### ISSUE TITLE
Not working on ldplayer (forward assault)

### ISSUE THREAD

**Issue by 77friends** [reveny/Android-DLL-Injector#2]
![image](https://user-images.githubusercontent.com/115371071/194723146-bbc06ad0-ad1e-489a-9a5a-20a87efeab44.png)

I tried this on ldplayer, it doesn't seem to inject any lib into forward assault.

Is ldplayer/emulator support not added yet?

**Comment by reveny** [comment]
Make sure you are using a 32 bit emulator, not 64. I have tested it on ldplayer (android 9, 32 bit) and it works just fine.

**Comment by 77friends** [comment]
> Make sure you are using a 32 bit emulator, not 64. I have tested it on ldplayer (android 9, 32 bit) and it works just fine.

I tried using the 32 bit version of ldplayer 4, (shown below)

![image](https://user-images.githubusercontent.com/115371071/194727970-41a6d23c-6a1e-475a-a662-a00684245ae2.png)

When I do, I now get this error:

![image](https://user-images.githubusercontent.com/115371071/194728038-3e10bd63-9a03-4a8e-b550-3e8a0b783140.png)

**Comment by reveny** [comment]
I have checked again on LDPlayer 4 (Android 7, 32 Bit) and it works without any problems, keep in mind that the library you want to Inject needs to be located at "/data/local/tmp/" otherwise it will not work.
![Capture](https://user-images.githubusercontent.com/113244907/194753592-8ffb7c12-a9ae-49dc-a756-5c9a6bce0cc0.PNG)

**Comment by 77friends** [comment]
> I have checked again on LDPlayer 4 (Android 7, 32 Bit) and it works without any problems, keep in mind that the library you want to Inject needs to be located at "/data/local/tmp/" otherwise it will not work. ![Capture](https://user-images.githubusercontent.com/113244907/194753592-8ffb7c12-a9ae-49dc-a756-5c9a6bce0cc0.PNG)

Strange, because I have it in data/local/tmp and it does not inject, I get the same error. I am going to compile a fresh lib that doesn't do anything, and try injecting it (in case its an issue with the lib I'm injecting for whatever reason).

I will let you know if it works or not.

**Comment by reveny** [comment]
I have found the solution. You have to keep in mind that you can only Inject x86 libraries on x86 (ldplayer). Even if your game runs on 32 bit you have to build a x86 library to Inject.
